parameters:
- name: st_dependson
  type: object
- name: st_env
  type: string
- name: st_serviceconn
  type: string
- name: st_workingdir
  type: string
- name: st_backend_key
  type: string
- name: st_sub_project
  type: string

stages:
#- stage: plan_${{ parameters.st_env }}_${{ parameters.st_sub_project }}
#  displayName: "Dry-Run (Plan): ${{ parameters.st_env }} ${{ parameters.st_sub_project }}"
#  jobs:
#  - template: ../job/job-plan.yml
#    parameters:
#      env: ${{ parameters.st_env }}
#      dependson:
#      serviceconn: ${{ parameters.st_serviceconn }}
#      workingdir: ${{ parameters.st_workingdir }}
#      backend_key: ${{ parameters.st_backend_key }}
- stage: destroy_${{ parameters.st_env }}_${{ parameters.st_sub_project }}
  displayName: "Destroy: ${{ parameters.st_env }} ${{ parameters.st_sub_project }}"
  #dependsOn: plan_${{ parameters.st_env }}_${{ parameters.st_sub_project }}
  jobs:
  - template: ../job/job-destroy.yml
    parameters:
      env: ${{ parameters.st_env }}
      dependson:
      serviceconn: ${{ parameters.st_serviceconn }}
      workingdir: ${{ parameters.st_workingdir }}
      backend_key: ${{ parameters.st_backend_key }}