parameters:
- name: st_dependson
  type: object
- name: st_env
  type: string
- name: st_serviceconn
  type: string
- name: st_workingdir
  type: string
- name: st_backend_key
  type: string
- name: st_sub_project
  type: string
- name: st_run
  type: boolean
  default: true
- name: st_additional_vars
  type: string
  default: 

stages:
- stage: tmp
  jobs:
  - job: tmp
    variables:
    - group: environment
    - name: additional_vars
      ${{ if eq(parameters.st_sub_project, 'pbi_gateway') }}:
        value: "-var admin_password=$(PBI_GATEWAY_VM_PASSWORD) "
      ${{ elseif eq( parameters.st_sub_project, 'shared_shir' ) }}:
        value: "-var admin_password=$(SHIR_VM_PASSWORD) "
      ${{ elseif eq( parameters.st_sub_project, 'fivetran_integration' ) }}:
        value: "-var vm_admin_password=$(FIVETRAN_VM_PASSWORD) -var sql_admin_password=$(FIVETRAN_SQL_PASSWORD) "
      ${{ else }}:
        value: ""
    steps:
    - script: |    
       echo "test -> ${{ parameters.st_additional_vars }}"
       echo "param -> ${{ parameters.st_sub_project }}"
# - stage: plan_${{ parameters.st_env }}_${{ parameters.st_sub_project }}
#   displayName: "Dry-Run (Plan): ${{ parameters.st_env }} ${{ parameters.st_sub_project }}"
#   condition: and(succeeded(), eq(${{ parameters.st_run }}, true))
#   jobs:
#   - template: ../job/job-plan.yml
#     parameters:
#       env: ${{ parameters.st_env }}
#       dependson:
#       serviceconn: ${{ parameters.st_serviceconn }}
#       workingdir: ${{ parameters.st_workingdir }}
#       backend_key: ${{ parameters.st_backend_key }}
# - stage: deploy_${{ parameters.st_env }}_${{ parameters.st_sub_project }}
#   displayName: "Deployment: ${{ parameters.st_env }} ${{ parameters.st_sub_project }}"
#   condition: eq(${{ parameters.st_run }}, true)
#   jobs:
#   - template: ../job/job-apply-with-confirm.yml
#     parameters:
#       env: ${{ parameters.st_env }}
#       dependson:
#       serviceconn: ${{ parameters.st_serviceconn }}
#       workingdir: ${{ parameters.st_workingdir }}
#       backend_key: ${{ parameters.st_backend_key }}
#       additional_vars: ${{ parameters.st_additional_vars }}