trigger: none

pool:
  name: aks-infra

name: $(Date:yyyyMMdd).$(Rev:r) (cdmz_deployment)

variables:
  - group: environment
  - group: backend

stages:

- template: templates/stage/stages-deploy.yml
  parameters:
    st_serviceconn: CDP_Management
    st_env: prod
    st_dependson: deploy_prod_resource_groups
    st_workingdir: '$(System.DefaultWorkingDirectory)/projects/cdmz/networking/'
    st_backend_key: 'prod/cdmz/cdmz_networking.tfstate'
    st_sub_project: networking