trigger: none

pool:
  name: aks-infra

name: $(Date:yyyyMMdd).$(Rev:r) (cdmz_destroy)

variables:
  - group: environment
  - group: backend

stages:

- template: templates/stage/stages-destroy.yml
  parameters:
    st_serviceconn: CDP_Management
    st_env: prod
    st_dependson:
    st_workingdir: '$(System.DefaultWorkingDirectory)/projects/cdmz/permissions/'
    st_backend_key: 'prod/cdmz/permissions.tfstate'
    st_sub_project: permissions

- template: templates/stage/stages-destroy.yml
  parameters:
    st_serviceconn: CDP_Management
    st_env: prod
    st_dependson: destroy_prod_permissions
    st_workingdir: '$(System.DefaultWorkingDirectory)/projects/cdmz/monitoring/'
    st_backend_key: 'prod/cdmz/monitoring.tfstate'
    st_sub_project: monitoring

- template: templates/stage/stages-destroy.yml
  parameters:
    st_serviceconn: CDP_Management
    st_env: prod
    st_dependson: destroy_prod_monitoring
    st_workingdir: '$(System.DefaultWorkingDirectory)/projects/cdmz/fivetran-integration/'
    st_backend_key: 'prod/cdmz/fivetran-integration.tfstate'
    st_sub_project: fivetran_integration

- template: templates/stage/stages-destroy.yml
  parameters:
    st_serviceconn: CDP_Management
    st_env: prod
    st_dependson: destroy_prod_monitoring
    st_workingdir: '$(System.DefaultWorkingDirectory)/projects/cdmz/management/'
    st_backend_key: 'prod/cdmz/management.tfstate'
    st_sub_project: management

- template: templates/stage/stages-destroy.yml
  parameters:
    st_serviceconn: CDP_Management
    st_env: prod
    st_dependson: destroy_prod_monitoring
    st_workingdir: '$(System.DefaultWorkingDirectory)/projects/cdmz/pbi-gateway/'
    st_backend_key: 'prod/cdmz/pbi-gateway.tfstate'
    st_sub_project: pbi_gateway

- template: templates/stage/stages-destroy.yml
  parameters:
    st_serviceconn: CDP_Management
    st_env: prod
    st_dependson: destroy_prod_monitoring
    st_workingdir: '$(System.DefaultWorkingDirectory)/projects/cdmz/shared-shir/'
    st_backend_key: 'prod/cdmz/shared-shir.tfstate'
    st_sub_project: shared_shir

- template: templates/stage/stages-destroy.yml
  parameters:
    st_serviceconn: CDP_Management
    st_env: prod
    st_dependson: destroy_prod_monitoring
    st_workingdir: '$(System.DefaultWorkingDirectory)/projects/cdmz/networking/'
    st_backend_key: 'prod/cdmz/cdmz_networking.tfstate'
    st_sub_project: networking